import React, { useState, useEffect } from 'react';
import { useAuth } from '../../context/AuthContext';
import { useAlert } from '../../context/AlertContext';
import api from '../../api/client';
import { EmergencyEvent } from '../../types';
import {
  AlertOctagon,
  ShieldAlert,
  Clock,
  MapPin,
  CheckCircle,
  Filter,
  CheckCheck,
} from 'lucide-react';

export const CaregiverAlertsPage: React.FC = () => {
  const { activePatientId } = useAuth();
  const { acknowledgeEmergency, resolveEmergency } = useAlert();

  const [emergencies, setEmergencies] = useState<EmergencyEvent[]>([]);
  const [filter, setFilter] = useState<'ALL' | 'ACTIVE' | 'RESOLVED'>('ALL');
  const [loading, setLoading] = useState(true);

  const fetchEmergencies = () => {
    if (!activePatientId) return;

    api.get(`/emergency/history/${activePatientId}`)
      .then((res) => {
        if (res.data?.data) setEmergencies(res.data.data);
      })
      .catch((err) => console.error(err))
      .finally(() => setLoading(false));
  };

  useEffect(() => {
    fetchEmergencies();
  }, [activePatientId]);

  const filtered = emergencies.filter((e) => {
    if (filter === 'ACTIVE') return e.status === 'ACTIVE' || e.status === 'ACKNOWLEDGED';
    if (filter === 'RESOLVED') return e.status === 'RESOLVED' || e.status === 'CANCELLED';
    return true;
  });

  return (
    <div className="space-y-8 pb-12">
      {/* Header */}
      <div className="bg-white rounded-3xl p-6 sm:p-8 border-2 border-slate-200 shadow-sm flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <span className="text-xs font-bold text-red-600 uppercase tracking-widest block">Safety Incident Log</span>
          <h1 className="text-3xl font-black text-slate-900 mt-1">Alerts & Emergency Events</h1>
          <p className="text-sm text-slate-500 mt-1">
            Real-time notifications generated by manual SOS, fall verification, and safety rule thresholds
          </p>
        </div>

        {/* Filter Pills */}
        <div className="flex items-center gap-2 bg-slate-100 p-1.5 rounded-2xl border border-slate-200">
          {(['ALL', 'ACTIVE', 'RESOLVED'] as const).map((mode) => (
            <button
              key={mode}
              onClick={() => setFilter(mode)}
              className={`px-4 py-2 rounded-xl text-xs font-bold transition-all cursor-pointer ${
                filter === mode ? 'bg-teal-600 text-white shadow-sm' : 'text-slate-600 hover:text-slate-900'
              }`}
            >
              {mode}
            </button>
          ))}
        </div>
      </div>

      {/* Events List */}
      <div className="space-y-4">
        {loading ? (
          <div className="text-center py-12 text-slate-400">Loading incident records...</div>
        ) : filtered.length === 0 ? (
          <div className="text-center py-12 text-slate-400">No emergency events found for this filter.</div>
        ) : (
          filtered.map((item) => {
            const isCritical = item.severity === 'CRITICAL';
            const isActive = item.status === 'ACTIVE';

            return (
              <div
                key={item.id}
                className={`elderly-card border-l-8 flex flex-col sm:flex-row sm:items-center justify-between gap-6 ${
                  isActive
                    ? 'border-l-red-600 bg-red-50/40 animate-pulse-slow'
                    : item.status === 'ACKNOWLEDGED'
                    ? 'border-l-amber-500 bg-amber-50/20'
                    : 'border-l-slate-300 bg-white'
                }`}
              >
                <div className="flex items-start gap-4">
                  <div
                    className={`w-14 h-14 rounded-2xl flex items-center justify-center shrink-0 ${
                      isCritical ? 'bg-red-100 text-red-700' : 'bg-amber-100 text-amber-700'
                    }`}
                  >
                    <ShieldAlert className="w-8 h-8" />
                  </div>

                  <div>
                    <div className="flex items-center gap-2">
                      <h3 className="text-xl font-black text-slate-900">{item.type} Emergency</h3>
                      <span
                        className={`text-xs font-bold px-2.5 py-0.5 rounded-full uppercase ${
                          isActive
                            ? 'bg-red-600 text-white'
                            : item.status === 'RESOLVED'
                            ? 'bg-emerald-100 text-emerald-800'
                            : 'bg-amber-100 text-amber-800'
                        }`}
                      >
                        {item.status}
                      </span>
                    </div>

                    <p className="text-sm text-slate-700 mt-1 font-medium">{item.notes || 'Emergency event logged'}</p>

                    <div className="flex items-center gap-4 text-xs text-slate-500 mt-2">
                      <span className="flex items-center gap-1">
                        <MapPin className="w-3.5 h-3.5 text-teal-600" />
                        {item.location || 'Home'}
                      </span>
                      <span className="flex items-center gap-1">
                        <Clock className="w-3.5 h-3.5 text-teal-600" />
                        {new Date(item.timestamp).toLocaleString()}
                      </span>
                    </div>
                  </div>
                </div>

                {/* Actions */}
                <div className="flex items-center gap-2 self-end sm:self-center shrink-0">
                  {item.status === 'ACTIVE' && (
                    <button
                      onClick={async () => {
                        await acknowledgeEmergency(item.id);
                        fetchEmergencies();
                      }}
                      className="bg-amber-500 hover:bg-amber-600 text-white text-xs font-bold px-4 py-2.5 rounded-xl shadow cursor-pointer"
                    >
                      Acknowledge
                    </button>
                  )}

                  {item.status !== 'RESOLVED' && item.status !== 'CANCELLED' && (
                    <button
                      onClick={async () => {
                        await resolveEmergency(item.id, 'Resolved from Caregiver Portal');
                        fetchEmergencies();
                      }}
                      className="bg-teal-600 hover:bg-teal-700 text-white text-xs font-bold px-5 py-2.5 rounded-xl shadow cursor-pointer flex items-center gap-1.5"
                    >
                      <CheckCircle className="w-4 h-4" />
                      <span>Resolve</span>
                    </button>
                  )}
                </div>
              </div>
            );
          })
        )}
      </div>
    </div>
  );
};
